version: "3"

services:
  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: []
    command: sh docker/start.sh
    volumes: 
      - .:/app
      - ./bundle_data:/bundle
    ports:
      - "3000:3000"
    env_file:
      - web.env
    depends_on: 
      - db

  db:
    image: mysql:5.7
    restart: on-failure
    ports:
      - "3306:3306"
    env_file:
      - web.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME_PROD}
      - MYSQL_USER=${DB_USER}
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf

volumes:
  mysql_data:
  bundle_data: